### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735908736

### CODE REVIEW

**Comment by fridex** [comment]
This one will require also base image bump so that we use Python 3.8 in the built container image:

https://github.com/thoth-station/nepthys/blob/a745482b7fcdad97ba5b3202388e181525eb919b/Dockerfile#L2

**Comment by bissenbay** [comment]
> This one will require also base image bump so that we use Python 3.8 in the built container image:
> 
> https://github.com/thoth-station/nepthys/blob/a745482b7fcdad97ba5b3202388e181525eb919b/Dockerfile#L2

@fridex should I use `FROM fedora:32`?

**Comment by fridex** [comment]
> > This one will require also base image bump so that we use Python 3.8 in the built container image:
> > https://github.com/thoth-station/nepthys/blob/a745482b7fcdad97ba5b3202388e181525eb919b/Dockerfile#L2
> 
> @fridex should I use `FROM fedora:32`?

You can try it. :+1: I think all the packages required will not be available in ubi (e.g. hub).

And maybe use fedora registry:

```dockerfile
FROM registry.fedoraproject.org/fedora:32
```

**Comment by bissenbay** [comment]
> > > This one will require also base image bump so that we use Python 3.8 in the built container image:
> > > https://github.com/thoth-station/nepthys/blob/a745482b7fcdad97ba5b3202388e181525eb919b/Dockerfile#L2
> > 
> > 
> > @fridex should I use `FROM fedora:32`?
> 
> You can try it.  I think all the packages required will not be available in ubi (e.g. hub).
> 
> And maybe use fedora registry:
> 
> ```dockerfile
> FROM registry.fedoraproject.org/fedora:32
> ```

@fridex I did the change and it was built successfully locally, PTAL https://github.com/thoth-station/nepthys/pull/55/commits/8ecdb6a0e67bf7e2f434d6b0c6948fcbe3cfb319

**Review by fridex — APPROVED** [review]
lgtm, thanks! :+1:

**Pull request merged**
